Rigid Body Dynamics Library: Constraints
Constraints
Data Structures
struct ConstraintSet
Structure that contains both constraint information and workspace memory.
Functions
ConstraintSet ()
unsigned int getGroupIndexByName (const char *userDefinedName)
getGroupIndex returns the index to a constraints that have been grouped because they are of the same type, apply to the same bodies, and apply to the same local frames on each body.
unsigned int getGroupIndexById (unsigned int userDefinedId)
getGroupIndex returns the index to a constraints that have been grouped because they are of the same type, apply to the same bodies, and apply to the same local frames on each body.
unsigned int getGroupIndexByAssignedId (unsigned int assignedId)
getGroupIndex returns the index to a constraints that have been grouped because they are of the same type, apply to the same bodies, and apply to the same local frames on each body.
unsigned int getGroupIndexMax ()
getGroupIndexMax returns the maximum valid constraint group index (the min. is zero) so that constraint groups can be iterated over if desired.
const char * getGroupName (unsigned int groupIndex)
Returns the name of the constraint group, which may differ from the names entered by the user if the constraint is one in which grouping is done automatically (e.g. contact and loop constraints)
unsigned int getGroupSize (unsigned int groupIndex)
Returns the number of constraint equations in this group.
unsigned int getGroupType (unsigned int groupIndex)
Returns integer corresponding to the ConstraintType.
unsigned int getGroupId (unsigned int groupIndex)
Returns the user-defined-id of the constraint group, which may differ from the names entered by the user if the constraint is one in which grouping is done automatically (e.g. contact and loop constraints).
unsigned int getGroupAssignedId (unsigned int groupIndex)
Returns assigned id of the constraint group which will be the first id assigned to an entry in a group (if the grouping was done automatically - as is done for contact and loop constraints).
void calcForces (unsigned int groupIndex, Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, std::vector< unsigned int > &updConstraintBodyIdsOutput, std::vector< Math::SpatialTransform > &updConstraintBodyFramesOutput, std::vector< Math::SpatialVector > &updConstraintForcesOutput, bool resolveAllInRootFrame=false, bool updateKinematics=false)
calcForces resolves the generalized forces generated by this constraint into equivalent spatial forces (resolved in the local or the base frame) that are applied between the bodies and frames that this constraint applies to.
void calcImpulses (unsigned int groupIndex, Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, std::vector< unsigned int > &constraintBodyIdsOutput, std::vector< Math::SpatialTransform > &constraintBodyFramesOutput, std::vector< Math::SpatialVector > &constraintImpulsesOutput, bool resolveAllInRootFrame=false, bool updateKinematics=false)
calcImpulses resolves the generalized impluses generated by this constraint into equivalent spatial impulses (resolved in the local or the base frame) that are applied between the bodies and frames that this constraint applies to.
void calcPositionError (unsigned int groupIndex, Model &model, const Math::VectorNd &Q, Math::VectorNd &positionErrorOutput, bool updateKinematics=false)
calcPositionError calculates the vector of position errors associated with this constraint. Note that if the constraint group, or parts of it, are not defined at the position level then 0's will be returned.
void calcVelocityError (unsigned int groupIndex, Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, Math::VectorNd &velocityErrorOutput, bool updateKinematics=false)
calcVelocityError calculates the vector of position errors associated with this constraint. Note that if the constraint group, or parts of it, are not defined at the position level then 0's will be returned.
void calcBaumgarteStabilizationForces (unsigned int groupIndex, Model &model, const Math::VectorNd &positionError, const Math::VectorNd &velocityError, Math::VectorNd &baumgarteForcesOutput)
bool isBaumgarteStabilizationEnabled (unsigned int groupIndex)
void enableBaumgarteStabilization (unsigned int groupIndex)
void disableBaumgarteStabilization (unsigned int groupIndex)
void getBaumgarteStabilizationCoefficients (unsigned int groupIndex, Math::Vector2d &baumgartePositionVelocityCoefficientsOutput)
unsigned int AddContactConstraint (unsigned int bodyId, const Math::Vector3d &bodyPoint, const Math::Vector3d &worldNormal, const char *constraintName=NULL, unsigned int userDefinedId=std::numeric_limits< unsigned int >::max())
Adds a single contact constraint (point-ground) to the constraint set.
unsigned int AddLoopConstraint (unsigned int bodyIdPredecessor, unsigned int bodyIdSuccessor, const Math::SpatialTransform &XPredecessor, const Math::SpatialTransform &XSuccessor, const Math::SpatialVector &constraintAxisInPredecessor, bool enableBaumgarteStabilization=false, double stabilizationTimeConstant=0.1, const char *constraintName=NULL, unsigned int userDefinedId=std::numeric_limits< unsigned int >::max())
Adds a loop constraint to the constraint set.
unsigned int AddCustomConstraint (std::shared_ptr< Constraint > customConstraint)
Adds a custom constraint to the constraint set.
ConstraintSet Copy ()
Copies the constraints and resets its ConstraintSet::bound flag.
void SetSolver (Math::LinearSolver solver)
Specifies which method should be used for solving undelying linear systems.
bool Bind (const Model &model)
Initializes and allocates memory for the constraint set.
void SetActuationMap (const Model &model, const std::vector< bool > &actuatedDof)
Initializes and allocates memory needed for InverseDynamicsConstraints and InverseDynamicsConstraintsRelaxed.
size_t size () const
Returns the number of constraints.
void clear ()
Clears all variables in the constraint set.
RBDL_DLLAPI void CalcConstraintsPositionError (Model &model, const Math::VectorNd &Q, ConstraintSet &CS, Math::VectorNd &errOutput, bool update_kinematics=true)
Computes the position errors for the given ConstraintSet.
RBDL_DLLAPI void CalcConstraintsJacobian (Model &model, const Math::VectorNd &Q, ConstraintSet &CS, Math::MatrixNd &GOutput, bool update_kinematics=true)
Computes the Jacobian for the given ConstraintSet.
RBDL_DLLAPI void CalcConstraintsVelocityError (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, ConstraintSet &CS, Math::VectorNd &errOutput, bool update_kinematics=true)
Computes the velocity errors for the given ConstraintSet.
RBDL_DLLAPI void CalcConstrainedSystemVariables (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, const Math::VectorNd &Tau, ConstraintSet &CSOutput, std::vector< Math::SpatialVector > *f_ext=NULL)
Computes the terms , , and of the constrained dynamic problem and stores them in the ConstraintSet.
RBDL_DLLAPI bool CalcAssemblyQ (Model &model, Math::VectorNd QInit, ConstraintSet &CS, Math::VectorNd &QOutput, const Math::VectorNd &weights, double tolerance=1e-12, unsigned int max_iter=100)
Computes a feasible initial value of the generalized joint positions.
RBDL_DLLAPI void CalcAssemblyQDot (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDotInit, ConstraintSet &CS, Math::VectorNd &QDotOutput, const Math::VectorNd &weights)
Computes a feasible initial value of the generalized joint velocities.
RBDL_DLLAPI void ForwardDynamicsConstraintsDirect (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, const Math::VectorNd &Tau, ConstraintSet &CS, Math::VectorNd &QDDotOutput, std::vector< Math::SpatialVector > *f_ext=NULL)
Computes forward dynamics with contact by constructing and solving the full lagrangian equation.
RBDL_DLLAPI void ForwardDynamicsConstraintsRangeSpaceSparse (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, const Math::VectorNd &Tau, ConstraintSet &CS, Math::VectorNd &QDDot, std::vector< Math::SpatialVector > *f_ext)
RBDL_DLLAPI void ForwardDynamicsConstraintsNullSpace (Model &model, const VectorNd &Q, const VectorNd &QDot, const VectorNd &Tau, ConstraintSet &CS, VectorNd &QDDot, std::vector< Math::SpatialVector > *f_ext)
RBDL_DLLAPI void ForwardDynamicsContactsKokkevis (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, const Math::VectorNd &Tau, ConstraintSet &CS, Math::VectorNd &QDDotOutput)
Computes forward dynamics that accounts for active contacts in ConstraintSet.
RBDL_DLLAPI void InverseDynamicsConstraintsRelaxed (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, const Math::VectorNd &QDDotControls, ConstraintSet &CS, Math::VectorNd &QDDotOutput, Math::VectorNd &TauOutput, std::vector< Math::SpatialVector > *f_ext=NULL)
A relaxed inverse-dynamics operator that can be applied to under-actuated or fully-actuated constrained multibody systems.
RBDL_DLLAPI void InverseDynamicsConstraints (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, const Math::VectorNd &QDDotDesired, ConstraintSet &CS, Math::VectorNd &QDDotOutput, Math::VectorNd &TauOutput, std::vector< Math::SpatialVector > *f_ext=NULL)
An inverse-dynamics operator that can be applied to fully-actuated constrained systems.
RBDL_DLLAPI bool isConstrainedSystemFullyActuated (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDot, ConstraintSet &CS, std::vector< Math::SpatialVector > *f_ext=NULL)
A method to evaluate if the constrained system is fully actuated.
RBDL_DLLAPI void ComputeConstraintImpulsesDirect (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDotMinus, ConstraintSet &CS, Math::VectorNd &QDotPlusOutput)
Computes contact gain by constructing and solving the full lagrangian equation.
RBDL_DLLAPI void ComputeConstraintImpulsesRangeSpaceSparse (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDotMinus, ConstraintSet &CS, Math::VectorNd &QDotPlusOutput)
Resolves contact gain using SolveContactSystemRangeSpaceSparse()
RBDL_DLLAPI void ComputeConstraintImpulsesNullSpace (Model &model, const Math::VectorNd &Q, const Math::VectorNd &QDotMinus, ConstraintSet &CS, Math::VectorNd &QDotPlusOutput)
Resolves contact gain using SolveContactSystemNullSpace()
RBDL_DLLAPI void SolveConstrainedSystemDirect (Math::MatrixNd &H, const Math::MatrixNd &G, const Math::VectorNd &c, const Math::VectorNd &gamma, Math::VectorNd &lambda, Math::MatrixNd &A, Math::VectorNd &b, Math::VectorNd &x, Math::LinearSolver &linear_solver)
Solves the full contact system directly, i.e. simultaneously for contact forces and joint accelerations.
RBDL_DLLAPI void SolveConstrainedSystemRangeSpaceSparse (Model &model, Math::MatrixNd &H, const Math::MatrixNd &G, const Math::VectorNd &c, const Math::VectorNd &gamma, Math::VectorNd &qddot, Math::VectorNd &lambda, Math::MatrixNd &K, Math::VectorNd &a, Math::LinearSolver linear_solver)
Solves the contact system by first solving for the the joint accelerations and then the contact forces using a sparse matrix decomposition of the joint space inertia matrix.
RBDL_DLLAPI void SolveConstrainedSystemNullSpace (Math::MatrixNd &H, const Math::MatrixNd &G, const Math::VectorNd &c, const Math::VectorNd &gamma, Math::VectorNd &qddot, Math::VectorNd &lambda, Math::MatrixNd &Y, Math::MatrixNd &Z, Math::VectorNd &qddot_y, Math::VectorNd &qddot_z, Math::LinearSolver &linear_solver)
Solves the contact system by first solving for the joint accelerations and then for the constraint forces.
Variables
Math::LinearSolver linear_solver
Method that should be used to solve internal linear systems.
bool bound
Whether the constraint set was bound to a model (mandatory!).
std::vector< ConstraintType > constraintType
std::vector< std::string > name
std::map< std::string, unsigned int > nameGroupMap
std::map< unsigned int, unsigned int > userDefinedIdGroupMap
std::map< unsigned int, unsigned int > idGroupMap
std::vector< std::shared_ptr< Constraint > > constraints
std::vector< std::shared_ptr< ContactConstraint > > contactConstraints
std::vector< std::shared_ptr< LoopConstraint > > loopConstraints
Math::VectorNd err
Math::VectorNd errd
Math::VectorNd force
Math::VectorNd impulse
Constraint impulses along the constraint directions.
Math::VectorNd v_plus
The velocities we want to have along the constraint directions.
Math::MatrixNd H
Workspace for the joint space inertia matrix.
Math::VectorNd C
Workspace for the coriolis forces.
Math::VectorNd gamma
Workspace of the right hand side of the acceleration equation.
Math::MatrixNd G
Workspace for the constraint Jacobian.
Math::MatrixNd A
Workspace for the Lagrangian left-hand-side matrix.
Math::VectorNd b
Workspace for the Lagrangian right-hand-side.
Math::VectorNd x
Workspace for the Lagrangian solution.
Math::MatrixNd S
Math::MatrixNd P
Selection matrix for the non-actuated parts of the model.
Math::MatrixNd W
Math::MatrixNd Winv
Math::VectorNd WinvSC
Math::VectorNd u
Math::VectorNd v
Math::MatrixNd F
Math::MatrixNd Ful
Math::MatrixNd Fur
Math::MatrixNd Fll
Math::MatrixNd Flr
Math::MatrixNd GT
Math::MatrixNd GTu
Math::MatrixNd GTl
Math::VectorNd g
Math::MatrixNd Ru
Math::VectorNd py
Math::VectorNd pz
Eigen::HouseholderQR< Math::MatrixNd > GT_qr
Workspace for the QR decomposition of the null-space method.
Eigen::FullPivHouseholderQR< Math::MatrixNd > GPT_full_qr
Math::MatrixNd GT_qr_Q
Math::MatrixNd GPT
Math::MatrixNd Y
Math::MatrixNd Z
Math::MatrixNd R
Math::VectorNd qddot_y
Math::VectorNd qddot_z
Math::MatrixNd K
Workspace for the Inverse Articulated-Body Inertia.
Math::VectorNd a
Workspace for the accelerations of due to the test forces.
Math::VectorNd QDDot_t
Workspace for the test accelerations.
Math::VectorNd QDDot_0
Workspace for the default accelerations.
std::vector< Math::SpatialVector > f_t
Workspace for the test forces.
std::vector< Math::SpatialVector > f_ext_constraints
Workspace for the actual spatial forces.
std::vector< Math::Vector3d > point_accel_0
Workspace for the default point accelerations.
std::vector< Math::SpatialVector > d_pA
Workspace for the bias force due to the test force.
std::vector< Math::SpatialVector > d_a
Workspace for the acceleration due to the test force.
Math::VectorNd d_u
std::vector< Math::SpatialMatrix > d_IA
Workspace for the inertia when applying constraint forces.
std::vector< Math::SpatialVector > d_U
Workspace when applying constraint forces.
Math::VectorNd d_d
Workspace when applying constraint forces.
std::vector< Math::Vector3d > d_multdof3_u
ConstraintCache cache
Detailed Description
Constraints are handled by specification of a ConstraintSet which contains all information about the current constraints and workspace memory.
Separate constraints can be specified by calling ConstraintSet::AddContactConstraint(), ConstraintSet::AddLoopConstraint(), and ConstraintSet::AddCustomConstraint(). After all constraints have been specified, this ConstraintSet has to be bound to the model via ConstraintSet::Bind(). This initializes workspace memory that is later used when calling one of the contact functions, such as ForwardDynamicsContactsDirects().
The values in the vectors ConstraintSet::force and ConstraintSet::impulse contain the Lagrange multipliers or change in Lagrange multipliers for each constraint when returning from one of the contact functions.
Solution of the Constraint System
Linear System of the Constrained Dynamics
In the presence of constraints, to compute the acceleration one has to solve a linear system of the form:
where is the joint space inertia matrix computed with the CompositeRigidBodyAlgorithm(), is the constraint Jacobian, the bias force (sometimes called "non-linear effects"), and the generalized acceleration independent part of the constraints.
Linear System of the Constraint Impacts
Similarly to compute the response of the model to a constraint gain one has to solve a system of the following form:
where is the joint space inertia matrix computed with the CompositeRigidBodyAlgorithm(), are the Jacobians of the constraints, the generalized velocity after the impact, the impulses at each constraint, the generalized velocity before the impact, and the desired velocity of each constraint after the impact (known beforehand, usually 0). The value of can is specified via the variable ConstraintSet::v_plus and defaults to 0.
Solution Methods
There are essentially three different approaches to solve these systems:
Direct: solve the full system to simultaneously compute and . This may be slow for large systems and many constraints.
Range-Space: solve first for and then for .
Null-Space: solve furst for and then for The methods are the same for the contact gains just with different variables on the right-hand-side.
RBDL provides methods for all approaches. The implementation for the range-space method also exploits sparsities in the joint space inertia matrix using a sparse structure preserving decomposition as described in Chapter 8.5 of "Rigid Body Dynamics Algorithms".
None of the methods is generally superior to the others and each has different trade-offs as factors such as model topology, number of constraints, constrained bodies, numerical stability, and performance vary and evaluation has to be made on a case-by-case basis.
Methods for Solving Constrained
Dynamics
RBDL provides the following methods to compute the acceleration of a constrained system:
ForwardDynamicsConstraintsDirect()
ForwardDynamicsConstraintsRangeSpaceSparse()
ForwardDynamicsConstraintsNullSpace()
Methods for Computing Collisions
RBDL provides the following methods to compute the collision response on new contact gains:
ComputeConstraintImpulsesDirect()
ComputeConstraintImpulsesRangeSpaceSparse()
ComputeConstraintImpulsesNullSpace()
Computing generalized joint positions and velocities
satisfying the constraint equations.
When considering a model subject position level constraints expressed by the equation , it is often necessary to compute generalized joint position and velocities which satisfy the constraints. Even velocity-level constraints may have position-level assembly constraints: a rolling-without-slipping constraint is a velocity-level constraint, but during assembly it might be desireable to put the rolling surfaces in contact with eachother.
In order to compute a vector of generalized joint positions that satisfy the constraints it is necessary to solve the following optimization problem:
In order to compute a vector of generalized joint velocities that satisfy the constraints it is necessary to solve the following optimization problem:
and are initial guesses, is the constraints Jacobian (partial derivative of with respect to), and is the partial derivative of with respect to time. is a diagonal weighting matrix, which can be exploited to prioritize changes in the position/ velocity of specific joints. With a solver capable of handling singular matrices, it is possible to set to 1 the weight of the joint positions/ velocities that should not be changed from the initial guesses, and to 0 those corresponding to the values that can be changed.
These problems are solved using the Lagrange multipliers method. For the velocity problem the solution is exact. For the position problem the constraints are linearized in the form and the linearized problem is solved iteratively until the constraint position errors are smaller than a given threshold.
RBDL provides two functions to compute feasible joint position and velocities:
CalcAssemblyQ()
CalcAssemblyQDot()
Baumgarte Stabilization
The constrained dynamic equations are correct at the acceleration level but will drift at the velocity and position level during numerical integration. RBDL implements Baumgarte stabilization to avoid the accumulation of position and velocity errors for loop constraints and custom constraints. Contact constraints do not have Baumgarte stabilization because they are a special case which does not typically suffer from drift. The stabilization term can be enabled/disabled using the appropriate ConstraintSet::AddLoopConstraint and ConstraintSet::AddCustomConstraint functions.
The dynamic equations are changed to the following form:
A term is added to the right hand side of the equation, defined in the following way:
where are the position level constraint errors and and are tuning coefficients. There is no clear and simple rule on how to choose them as good values also depend on the used integration method and time step. If the values are too small the constrained dynamics equation becomes stiff, too big values result in errors not being reduced.
A good starting point is to parameterize the coefficients as:
with specifies a time constant for errors in position and velocity errors to reduce. Featherstone suggests in his book "Rigid Body Dynamics Algorithms" that for a big industrial robot a value of 0.1 is reasonable. When testing different values best is to try different orders of magnitude as e.g. doubling a value only has little effect.
FBaumgarte stabilization is disabled by default, and uses the default the stabilization parameter .
Function Documentation
ConstraintSet()
ConstraintSet () inline
Definition at line 282 of file Constraints.h.
AddContactConstraint()
unsigned int AddContactConstraint (unsigned int bodyId, const Math::Vector3d & bodyPoint, const Math::Vector3d & worldNormal, const char * constraintName = NULL, unsigned int userDefinedId = std::numeric_limits<unsigned int>::max())
Adds a single contact constraint (point-ground) to the constraint set.
This type of constraints ensures that the velocity and acceleration of a specified body point along a specified axis are null.
Parameters
bodyId the body which is affected directly by the constraint
bodyPoint the point that is constrained relative to the contact body
worldNormal the normal direction in which to apply the constraint
constraintName a human readable name (optional, default: NULL). Set this field to a unique name (within this ConstraintSet) so that the function GetConstraintIndex can find it.
userDefinedId a user defined id (optional, defaults to max()). Set this field to a unique number (within this ConstraintSet) so that the function GetConstraintIndex can find it.
Definition at line 46 of file Constraints.cc.
References RigidBodyDynamics::ConstraintTypeContact.
AddCustomConstraint()
unsigned int AddCustomConstraint (std::shared_ptr< Constraint > customConstraint)
Adds a custom constraint to the constraint set.
Parameters
customConstraint The CustomConstraint to be added to the ConstraintSet
Definition at line 313 of file Constraints.cc.
References RigidBodyDynamics::ConstraintTypeCustom.
AddLoopConstraint()
unsigned int AddLoopConstraint (unsigned int bodyIdPredecessor, unsigned int bodyIdSuccessor, const Math::SpatialTransform & XPredecessor, const Math::SpatialTransform & XSuccessor, const Math::SpatialVector & constraintAxisInPredecessor, bool enableBaumgarteStabilization = false, double stabilizationTimeConstant = 0.1, const char * constraintName = NULL, unsigned int userDefinedId = std::numeric_limits<unsigned int>::max())
Adds a loop constraint to the constraint set.
This type of constraints ensures that the relative orientation and position, spatial velocity, and spatial acceleration between two frames in two bodies are null along a specified spatial constraint axis.
Parameters
bodyIdPredecessor the identifier of the predecessor body
bodyIdSuccessor the identifier of the successor body
XPredecessor a spatial transform localizing the constrained frames on the predecessor body, expressed with respect to the predecessor body frame. Note the position vector should be the r_BPB (from the body's origin, to the predessor frame, in the coordinates of the body's frame) and E_BP (the rotation matrix that will rotate vectors from the coordinates of the P frame to the coordinates of the body's frame).
XSuccessor a spatial transform localizing the constrained frames on the successor body, expressed with respect to the successor body frame. Note the position vector should be the r_BSB (from the body's origin, to the successor frame, in the coordinates of the body's frame) and E_BS (the rotation matrix that will rotate vectors from the coordinates of the S frame to the coordinates of the body's frame).
constraintAxisInPredecessor a spatial vector, resolved in the frame of the predecessor frame, indicating the axis along which the constraint acts
enableBaumgarteStabilization (optional, default false) setting this flag to true will modify the right hand side of the acceleration equation with a penaltiy term that is proportional to the constraint error scaled by a constant.
stabilizationTimeConstant (optional, defaults to 0.1 sec) this value scales the strength of Baumgarte stabilization so that the settling time of the error is proportional the value given here.
constraintName a human readable name (optional, default: NULL). Set this field to a unique name (within this ConstraintSet) so that the function GetConstraintIndex can find it.
userDefinedId a user defined id (optional, defaults to max()). Set this field to a unique number (within this ConstraintSet) so that the function GetConstraintIndex can find it.
Definition at line 166 of file Constraints.cc.
References RigidBodyDynamics::ConstraintTypeLoop, SpatialTransform::E, and SpatialTransform::r.
Bind()
bool Bind (const Model & model)
Initializes and allocates memory for the constraint set.
This function allocates memory for temporary values and matrices that are required for contact force computation. Both model and constraint set must not be changed after a binding as the required memory is dependent on the model size (i.e. the number of bodies and degrees of freedom) and the number of constraints in the Constraint set.
The values of ConstraintSet::acceleration may still be modified after the set is bound to the model.
Definition at line 392 of file Constraints.cc.
CalcAssemblyQ()
RBDL_DLLAPI bool CalcAssemblyQ (Model & model, Math::VectorNd QInit, ConstraintSet & CS, Math::VectorNd & QOutput, const Math::VectorNd & weights, double tolerance = 1e-12, unsigned int max_iter = 100)
Computes a feasible initial value of the generalized joint positions.
Parameters
model the model
QInit initial guess for the generalized positions of the joints
CS the constraint set for which the error should be computed
QOutput vector of the generalized joint positions.
weights weighting coefficients for the different joint positions.
tolerance the function will return successfully if the constraint position error norm is lower than this value.
max_iter the funciton will return unsuccessfully after performing this number of iterations.
Returns
true if the generalized joint positions were computed successfully, false otherwise.f
Definition at line 915 of file Constraints.cc.
References RigidBodyDynamics::CalcConstraintsJacobian(), RigidBodyDynamics::CalcConstraintsPositionError(), RigidBodyDynamics::JointTypeSpherical, ConstraintSet::linear_solver, Quaternion::omegaToQDot(), ConstraintSet::size(), and RigidBodyDynamics::SolveLinearSystem().
CalcAssemblyQDot()
RBDL_DLLAPI void CalcAssemblyQDot (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDotInit, ConstraintSet & CS, Math::VectorNd & QDotOutput, const Math::VectorNd & weights)
Computes a feasible initial value of the generalized joint velocities.
Parameters
model the model
Q the generalized joint position of the joints. It is assumed that this vector satisfies the position level assemblt constraints.
QDotInit initial guess for the generalized velocities of the joints
CS the constraint set for which the error should be computed
QDotOutput vector of the generalized joint velocities.
weights weighting coefficients for the different joint positions.
Definition at line 1016 of file Constraints.cc.
References RigidBodyDynamics::CalcConstraintsJacobian(), ConstraintSet::linear_solver, ConstraintSet::size(), and RigidBodyDynamics::SolveLinearSystem().
calcBaumgarteStabilizationForces()
void calcBaumgarteStabilizationForces (unsigned int groupIndex, Model & model, const Math::VectorNd & positionError, const Math::VectorNd & velocityError, Math::VectorNd & baumgarteForcesOutput)
Parameters
groupIndex the index number of this constraint (see getGroupIndex index functions)
model the multibody model
positionError the position errors associated with this constraint computed using the calcConstraintPositionError function
velocityError the velocity errors associated with this constraint computed using the calcConstraintVelocityError function
baumgarteForcesOutput (output) a reference to the vector of baumgarte stabilization forces applied to this this constraint.
Definition at line 2163 of file Constraints.cc.
CalcConstrainedSystemVariables()
RBDL_DLLAPI void CalcConstrainedSystemVariables (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, const Math::VectorNd & Tau, ConstraintSet & CSOutput, std::vector< Math::SpatialVector > * f_ext = NULL)
Computes the terms , , and of the constrained dynamic problem and stores them in the ConstraintSet.
Parameters
model the model
Q the generalized positions of the joints
QDot the generalized velocities of the joints
Tau the generalized forces of the joints
CSOutput the constraint set for which the error should be computed
f_ext External forces acting on the body in base coordinates (optional, defaults to NULL)
Note
This function is normally called automatically in the various constrained dynamics functions, the user normally does not have to call it.
Definition at line 861 of file Constraints.cc.
References ConstraintSet::C, ConstraintSet::cache, RigidBodyDynamics::CalcConstraintsJacobian(), RigidBodyDynamics::CalcConstraintsPositionError(), RigidBodyDynamics::CalcConstraintsVelocityError(), RigidBodyDynamics::CompositeRigidBodyAlgorithm(), ConstraintSet::constraints, ConstraintSet::err, ConstraintSet::errd, ConstraintSet::G, ConstraintSet::gamma, ConstraintSet::H, RigidBodyDynamics::NonlinearEffects(), ConstraintSet::QDDot_0, and RigidBodyDynamics::UpdateKinematicsCustom().
CalcConstraintsJacobian()
RBDL_DLLAPI void CalcConstraintsJacobian (Model & model, const Math::VectorNd & Q, ConstraintSet & CS, Math::MatrixNd & GOutput, bool update_kinematics = true)
Computes the Jacobian for the given ConstraintSet.
Parameters
model the model
Q the generalized positions of the joints
CS the constraint set for which the Jacobian should be computed
GOutput matrix where the output will be stored in
update_kinematics whether the kinematics of the model should be updated from Q
Definition at line 819 of file Constraints.cc.
References ConstraintSet::cache, ConstraintSet::constraints, RigidBodyDynamics::UpdateKinematicsCustom(), and ConstraintCache::vecNZeros.
CalcConstraintsPositionError()
RBDL_DLLAPI void CalcConstraintsPositionError (Model & model, const Math::VectorNd & Q, ConstraintSet & CS, Math::VectorNd & errOutput, bool update_kinematics = true)
Computes the position errors for the given ConstraintSet.
Parameters
model the model
Q the generalized positions of the joints
CS the constraint set for which the error should be computed
errOutput vector where the error will be stored in (should have the size of CS).
update_kinematics whether the kinematics of the model should be updated from Q.
Note
the position error is always 0 for contact constraints.
Definition at line 797 of file Constraints.cc.
References ConstraintSet::cache, ConstraintSet::constraints, ConstraintSet::size(), and RigidBodyDynamics::UpdateKinematicsCustom().
CalcConstraintsVelocityError()
RBDL_DLLAPI void CalcConstraintsVelocityError (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, ConstraintSet & CS, Math::VectorNd & errOutput, bool update_kinematics = true)
Computes the velocity errors for the given ConstraintSet.
Parameters
model the model
Q the generalized positions of the joints
QDot the generalized velocities of the joints
CS the constraint set for which the error should be computed
errOutput vector where the error will be stored in (should have the size of CS).
update_kinematics whether the kinematics of the model should be updated from Q.
Note
this is equivalent to multiplying the constraint Jacobian by the generalized velocities of the joints.
Definition at line 839 of file Constraints.cc.
References ConstraintSet::cache, RigidBodyDynamics::CalcConstraintsJacobian(), ConstraintSet::constraints, and ConstraintSet::G.
calcForces()
void calcForces (unsigned int groupIndex, Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, std::vector< unsigned int > & updConstraintBodyIdsOutput, std::vector< Math::SpatialTransform > & updConstraintBodyFramesOutput, std::vector< Math::SpatialVector > & updConstraintForcesOutput, bool resolveAllInRootFrame = false, bool updateKinematics = false)
calcForces resolves the generalized forces generated by this constraint into equivalent spatial forces (resolved in the local or the base frame) that are applied between the bodies and frames that this constraint applies to.
Note
Important: The values returned by this function are only valid after one of the dynamics methods (ForwardDynamicsConstraintsDirect, ForwardDynamicsConstraintsNullSpace, InverseDynamicsWithConstraints, etc) have been evaluated. Why? This function makes use of the Lagrange multipliers which are only evaluated when these dynamics-level functions are called.
Parameters
groupIndex the index number of this constraint (see getGroupIndex index functions)
model the multibody model
Q the generalized positions of the model
QDot the generalized velocities of the model
constraintBodyIdsOutputUpd a reference to a vector of body ids in which the spatial forces are resolved into. The ordering for the standard constraints are as follows :
ContactConstraint
[0] : body
[1] : ground
Loop Constraint
[0] : predecessor body
[1] : successor
constraintBodyFramesOutputUpd a reference to a vector of frames in which the spatial forces are resolved. The frame is located in the body id listed in constraintBodyIdsOutput.
constraintForcesOutputUpd a reference to a vector of spatial forces generated by this constraint. The spatial force is resolved into the frame listed in constraintBodyFramesOutput.
resolveAllInRootFrame
false: spatial forces are resolved into the local frames attached to the bodies involved in this constraint
true: spatial forces are resolved into the base frame. Note that this means that all entires in constraintBodyIdsOutput will be 0, the frames in constraintFramesOutput will have their origins at the contact frames but with directions that match the base frame.
updateKinematics setting this flag to true will trigger the kinematic transforms of the model to be updated.
Definition at line 2046 of file Constraints.cc.
References RigidBodyDynamics::UpdateKinematicsCustom().
calcImpulses()
void calcImpulses (unsigned int groupIndex, Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, std::vector< unsigned int > & constraintBodyIdsOutput, std::vector< Math::SpatialTransform > & constraintBodyFramesOutput, std::vector< Math::SpatialVector > & constraintImpulsesOutput, bool resolveAllInRootFrame = false, bool updateKinematics = false)
calcImpulses resolves the generalized impluses generated by this constraint into equivalent spatial impulses (resolved in the local or the base frame) that are applied between the bodies and frames that this constraint applies to.
Note
Important: The values returned by this function are only valid after one of the impulse methods (ComputeConstraintImpulsesDirect, ComputeConstraintImpulsesNullSpace, etc) have been evaluated. Why? This function makes use of the Lagrange multipliers which are only evaluated when these dynamics-level functions are called.
Parameters
groupIndex the index number of this constraint (see getGroupIndex index functions)
model the multibody model
Q the generalized positions of the model
QDot the generalized velocities of the model
constraintBodyIdsOutput a vector of body ids in which the spatial forces are resolved into. The ordering for the standard constraints are as follows :
ContactConstraint
[0] : body
[1] : ground
Loop Constraint
[0] : predecessor body
[1] : successor
constraintBodyFramesOutput a vector of frames in which the spatial forces are resolved. The frame is located in the body id listed in constraintBodyIdsOutput.
constraintImpulsesOutput a vector of spatial impulses generated by this constraint. The spatial impulse is resolved into the frame listed in constraintBodyFramesOutput.
resolveAllInRootFrame
false: spatial impulses are resolved into the local frames attached to the bodies involved in this constraint
true: spatial impulses are resolved into the base frame. Note that this means that all entires in constraintBodyIdsOutput will be 0, the frames in constraintFramesOutput will have their origins at the contact frames but with directions that match the base frame.
updateKinematics setting this flag to true will trigger the kinematic transforms of the model to be updated.
Definition at line 2074 of file Constraints.cc.
References RigidBodyDynamics::UpdateKinematicsCustom().
calcPositionError()
void calcPositionError (unsigned int groupIndex, Model & model, const Math::VectorNd & Q, Math::VectorNd & positionErrorOutput, bool updateKinematics = false)
calcPositionError calculates the vector of position errors associated with this constraint. Note that if the constraint group, or parts of it, are not defined at the position level then 0's will be returned.
Parameters
groupIndex the index number of this constraint (see getGroupIndex index functions)
model the multibody model
Q the generalized positions of the model
positionErrorOutput (output) a reference to the vector of constraint errors
updateKinematics setting this flag to true will trigger the kinematic transforms of the model to be updated.
Definition at line 2110 of file Constraints.cc.
References RigidBodyDynamics::UpdateKinematicsCustom().
calcVelocityError()
void calcVelocityError (unsigned int groupIndex, Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, Math::VectorNd & velocityErrorOutput, bool updateKinematics = false)
calcVelocityError calculates the vector of position errors associated with this constraint. Note that if the constraint group, or parts of it, are not defined at the position level then 0's will be returned.
Parameters
groupIndex the index number of this constraint (see getGroupIndex index functions)
model the multibody model
Q the generalized positions of the model
QDot the generalized velocities of the model
velocityErrorOutput (output) the vector of constraint errors at the velocity level
updateKinematics setting this flag to true will trigger the kinematic transforms of the model to be updated.
Definition at line 2134 of file Constraints.cc.
References RigidBodyDynamics::UpdateKinematicsCustom().
clear()
void clear ()
Clears all variables in the constraint set.
Definition at line 559 of file Constraints.cc.
ComputeConstraintImpulsesDirect()
RBDL_DLLAPI void ComputeConstraintImpulsesDirect (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDotMinus, ConstraintSet & CS, Math::VectorNd & QDotPlusOutput)
Computes contact gain by constructing and solving the full lagrangian equation.
This method builds and solves the linear system
where is the joint space inertia matrix computed with the CompositeRigidBodyAlgorithm(), are the point Jacobians of the contact points, the generalized velocity after the impact, the impulses at each constraint, the generalized velocity before the impact, and the desired velocity of each constraint after the impact (known beforehand, usually 0). The value of can is specified via the variable ConstraintSet::v_plus and defaults to 0.
Note
So far, only constraints acting along cartesian coordinate axes are allowed (i.e. (1, 0, 0), (0, 1, 0), and (0, 0, 1)). Also, one must not specify redundant constraints!
Note
To increase performance group constraints body and pointwise such that constraints acting on the same body point are sequentially in ConstraintSet. This can save computation of point Jacobians .
Parameters
model rigid body model
Q state vector of the internal joints
QDotMinus velocity vector of the internal joints before the impact
CS the set of active constraints
QDotPlusOutput velocities of the internals joints after the impact
Definition at line 1140 of file Constraints.cc.
References ConstraintSet::A, ConstraintSet::b, RigidBodyDynamics::CalcConstraintsJacobian(), RigidBodyDynamics::CompositeRigidBodyAlgorithm(), ConstraintSet::G, ConstraintSet::H, ConstraintSet::impulse, ConstraintSet::linear_solver, ConstraintSet::size(), RigidBodyDynamics::SolveConstrainedSystemDirect(), RigidBodyDynamics::UpdateKinematicsCustom(), ConstraintSet::v_plus, and ConstraintSet::x.
ComputeConstraintImpulsesNullSpace()
RBDL_DLLAPI void ComputeConstraintImpulsesNullSpace (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDotMinus, ConstraintSet & CS, Math::VectorNd & QDotPlusOutput)
Resolves contact gain using SolveContactSystemNullSpace()
Parameters
model rigid body model
Q state vector of the internal joints
QDotMinus velocity vector of the internal joints before the impact
CS the set of active constraints
QDotPlusOutput velocities of the internals joints after the impact
Definition at line 1196 of file Constraints.cc.
References RigidBodyDynamics::CalcConstraintsJacobian(), RigidBodyDynamics::CompositeRigidBodyAlgorithm(), ConstraintSet::G, ConstraintSet::GT_qr, ConstraintSet::GT_qr_Q, ConstraintSet::H, ConstraintSet::impulse, ConstraintSet::linear_solver, ConstraintSet::qddot_y, ConstraintSet::qddot_z, RigidBodyDynamics::SolveConstrainedSystemNullSpace(), RigidBodyDynamics::UpdateKinematicsCustom(), ConstraintSet::v_plus, ConstraintSet::Y, and ConstraintSet::Z.
ComputeConstraintImpulsesRangeSpaceSparse()
RBDL_DLLAPI void ComputeConstraintImpulsesRangeSpaceSparse (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDotMinus, ConstraintSet & CS, Math::VectorNd & QDotPlusOutput)
Resolves contact gain using SolveContactSystemRangeSpaceSparse()
Parameters
model rigid body model
Q state vector of the internal joints
QDotMinus velocity vector of the internal joints before the impact
CS the set of active constraints
QDotPlusOutput velocities of the internals joints after the impact
Definition at line 1173 of file Constraints.cc.
References ConstraintSet::a, RigidBodyDynamics::CalcConstraintsJacobian(), RigidBodyDynamics::CompositeRigidBodyAlgorithm(), ConstraintSet::G, ConstraintSet::H, ConstraintSet::impulse, ConstraintSet::K, ConstraintSet::linear_solver, RigidBodyDynamics::SolveConstrainedSystemRangeSpaceSparse(), RigidBodyDynamics::UpdateKinematicsCustom(), and ConstraintSet::v_plus.
Copy()
ConstraintSet Copy () inline
Copies the constraints and resets its ConstraintSet::bound flag.
Definition at line 798 of file Constraints.h.
References ConstraintSet::bound.
disableBaumgarteStabilization()
void disableBaumgarteStabilization (unsigned int groupIndex) inline
Parameters
groupIndex the index number of this constraint (see getGroupIndex index functions)
Definition at line 681 of file Constraints.h.
enableBaumgarteStabilization()
void enableBaumgarteStabilization (unsigned int groupIndex) inline
Parameters
groupIndex the index number of this constraint (see getGroupIndex index functions)
Definition at line 672 of file Constraints.h.
ForwardDynamicsConstraintsDirect()
RBDL_DLLAPI void ForwardDynamicsConstraintsDirect (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, const Math::VectorNd & Tau, ConstraintSet & CS, Math::VectorNd & QDDotOutput, std::vector< Math::SpatialVector > * f_ext = NULL)
Computes forward dynamics with contact by constructing and solving the full lagrangian equation.
This method builds and solves the linear system
where is the joint space inertia matrix computed with the CompositeRigidBodyAlgorithm(), are the point Jacobians of the contact points, the bias force (sometimes called "non-linear effects"), and the generalized acceleration independent part of the contact point accelerations.
Note
This function works with ContactConstraints, LoopConstraints and Custom Constraints. Nonetheless, this method will not tolerate redundant constraints.
Note
To increase performance group constraints body and pointwise such that constraints acting on the same body point are sequentially in ConstraintSet. This can save computation of point Jacobians .
Parameters
model rigid body model
Q state vector of the internal joints
QDot velocity vector of the internal joints
Tau actuations of the internal joints
CS the description of all acting constraints
QDDotOutput accelerations of the internals joints
f_ext External forces acting on the body in base coordinates (optional, defaults to NULL)
Note
During execution of this function values such as ConstraintSet::force get modified and will contain the value of the force acting along the normal.
Definition at line 1064 of file Constraints.cc.
References ConstraintSet::A, ConstraintSet::b, ConstraintSet::C, RigidBodyDynamics::CalcConstrainedSystemVariables(), ConstraintSet::force, ConstraintSet::G, ConstraintSet::gamma, ConstraintSet::H, ConstraintSet::linear_solver, ConstraintSet::size(), RigidBodyDynamics::SolveConstrainedSystemDirect(), and ConstraintSet::x.
ForwardDynamicsConstraintsNullSpace()
RBDL_DLLAPI void ForwardDynamicsConstraintsNullSpace (Model & model, const VectorNd & Q, const VectorNd & QDot, const VectorNd & Tau, ConstraintSet & CS, VectorNd & QDDot, std::vector< Math::SpatialVector > * f_ext)
Definition at line 1112 of file Constraints.cc.
References ConstraintSet::C, RigidBodyDynamics::CalcConstrainedSystemVariables(), ConstraintSet::force, ConstraintSet::G, ConstraintSet::gamma, ConstraintSet::GT_qr, ConstraintSet::GT_qr_Q, ConstraintSet::H, ConstraintSet::linear_solver, ConstraintSet::qddot_y, ConstraintSet::qddot_z, RigidBodyDynamics::SolveConstrainedSystemNullSpace(), ConstraintSet::Y, and ConstraintSet::Z.
ForwardDynamicsConstraintsRangeSpaceSparse()
RBDL_DLLAPI void ForwardDynamicsConstraintsRangeSpaceSparse (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, const Math::VectorNd & Tau, ConstraintSet & CS, Math::VectorNd & QDDot, std::vector< Math::SpatialVector > * f_ext)
Definition at line 1094 of file Constraints.cc.
References ConstraintSet::a, ConstraintSet::C, RigidBodyDynamics::CalcConstrainedSystemVariables(), ConstraintSet::force, ConstraintSet::G, ConstraintSet::gamma, ConstraintSet::H, ConstraintSet::K, ConstraintSet::linear_solver, and RigidBodyDynamics::SolveConstrainedSystemRangeSpaceSparse().
ForwardDynamicsContactsKokkevis()
RBDL_DLLAPI void ForwardDynamicsContactsKokkevis (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, const Math::VectorNd & Tau, ConstraintSet & CS, Math::VectorNd & QDDotOutput)
Computes forward dynamics that accounts for active contacts in ConstraintSet.
The method used here is the one described by Kokkevis and Metaxas in the Paper "Practical Physics for Articulated Characters", Game Developers Conference, 2004.
It does this by recursively computing the inverse articulated-body inertia (IABI) which is then used to build and solve a system of the form:
Here is the number of constraints and the method for building the system uses the Articulated Body Algorithm to efficiently compute entries of the system. The values are the constraint accelerations, the constraint forces, and are the constraint bias forces.
Parameters
model rigid body model
Q state vector of the internal joints
QDot velocity vector of the internal joints
Tau actuations of the internal joints
CS a list of all contact points
QDDotOutput accelerations of the internals joints
Note
During execution of this function values such as ConstraintSet::force get modified and will contain the value of the force acting along the normal.
This function supports only contact constraints.
Todo:
Allow for external forces
Definition at line 1539 of file Constraints.cc.
References ConstraintSet::a, ConstraintSet::cache, ConstraintSet::constraints, ConstraintSet::contactConstraints, ConstraintSet::f_ext_constraints, ConstraintSet::f_t, ConstraintSet::force, RigidBodyDynamics::ForwardDynamics(), RigidBodyDynamics::ForwardDynamicsAccelerationDeltas(), RigidBodyDynamics::ForwardDynamicsApplyConstraintForces(), RigidBodyDynamics::GetMovableBodyId(), ConstraintSet::K, ConstraintSet::linear_solver, LinearSolverColPivHouseholderQR, LinearSolverHouseholderQR, LinearSolverPartialPivLU, ConstraintSet::point_accel_0, ConstraintSet::QDDot_0, ConstraintSet::QDDot_t, ConstraintSet::size(), and RigidBodyDynamics::UpdateKinematicsCustom().
getBaumgarteStabilizationCoefficients()
void getBaumgarteStabilizationCoefficients (unsigned int groupIndex, Math::Vector2d & baumgartePositionVelocityCoefficientsOutput) inline
Definition at line 687 of file Constraints.h.
getGroupAssignedId()
unsigned int getGroupAssignedId (unsigned int groupIndex) inline
Returns assigned id of the constraint group which will be the first id assigned to an entry in a group (if the grouping was done automatically - as is done for contact and loop constraints).
Parameters
groupIndex the index number of a constraint group.
Returns
the assigned of the constraint group. For constraints that are grouped automatically (e.g. contact and loop constraints) the assigned id will be the assigned id fo the of the first constraint added to the group. For constraints which are not automatically grouped (e.g. CustomConstraints) the assigned id is identical to the one returned when the constraint was added to the constraint set (e.g. when AddCustomConstraint was called).
Definition at line 432 of file Constraints.h.
getGroupId()
unsigned int getGroupId (unsigned int groupIndex) inline
Returns the user-defined-id of the constraint group, which may differ from the names entered by the user if the constraint is one in which grouping is done automatically (e.g. contact and loop constraints).
Parameters
groupIndex the index number of a constraint group.
Returns
the user-defined-id of the constraint group. For constraints that are grouped automatically (e.g. contact and loop constraints) the user-defined-id will be the user-defined-id fo the of the first constraint added to the group. For constraints which are not automatically grouped (e.g. CustomConstraints) the user-defined-id is identical to the one the user assigned (optionally) when the constraint was added to the constraint set (e.g. when AddCustomConstraint was called).
Definition at line 411 of file Constraints.h.
getGroupIndexByAssignedId()
unsigned int getGroupIndexByAssignedId (unsigned int assignedId) inline
getGroupIndex returns the index to a constraints that have been grouped because they are of the same type, apply to the same bodies, and apply to the same local frames on each body.
Parameters
assignedId : the integer id that was returned when the constraint was added to the constraint set by the functions: AddContactConstraint, AddLoopConstraint, AddCustomConstraint, etc.
Returns
: the group index of the constraint
Definition at line 337 of file Constraints.h.
getGroupIndexById()
unsigned int getGroupIndexById (unsigned int userDefinedId) inline
getGroupIndex returns the index to a constraints that have been grouped because they are of the same type, apply to the same bodies, and apply to the same local frames on each body.
Parameters
userDefinedId : the optional integer id that was assigned to this constraint when it was created.
Returns
: the group index of the constraint
Definition at line 320 of file Constraints.h.
getGroupIndexByName()
unsigned int getGroupIndexByName (const char * userDefinedName) inline
getGroupIndex returns the index to a constraints that have been grouped because they are of the same type, apply to the same bodies, and apply to the same local frames on each body.
Note
Internally this function makes a temporary string. If speed is a concern then do not call this function in a loop: either save the index locally, use the userDefinedId (which is an integer), or use the assigned id (also an integer).
Parameters
userDefinedName : the optional name that the constraint was assigned when it was added to the constraint set.
Returns
: the group index of the constraint
Definition at line 304 of file Constraints.h.
getGroupIndexMax()
unsigned int getGroupIndexMax () inline
getGroupIndexMax returns the maximum valid constraint group index (the min. is zero) so that constraint groups can be iterated over if desired.
Returns
the largest group index
Definition at line 348 of file Constraints.h.
getGroupName()
const char* getGroupName (unsigned int groupIndex) inline
Returns the name of the constraint group, which may differ from the names entered by the user if the constraint is one in which grouping is done automatically (e.g. contact and loop constraints)
Parameters
groupIndex the index number of a constraint group.
Returns
the name of the constraint group. For constraints that are grouped automatically (e.g. contact and loop constraints) the group name is the name of the first constraint added to the group. For constraints which are not automatically grouped (e.g. CustomConstraints) the group name is identical to the optional name used when the constraint was added to the constraint set (e.g. when AddCustomConstraint was called).
Definition at line 368 of file Constraints.h.
getGroupSize()
unsigned int getGroupSize (unsigned int groupIndex) inline
Returns the number of constraint equations in this group.
Parameters
groupIndex the index number of a constraint group.
Returns
the number of constraint equations in this group. If this is a constraint where constraints are automatically grouped (e.g. contact and loop constraints) the size might be larger than you expect.
Definition at line 380 of file Constraints.h.
getGroupType()
unsigned int getGroupType (unsigned int groupIndex) inline
Returns integer corresponding to the ConstraintType.
Parameters
groupIndex the index number of a constraint group.
Returns
the integer that corresponds to the ConstraintType of this constraint group.
Definition at line 390 of file Constraints.h.
InverseDynamicsConstraints()
RBDL_DLLAPI void InverseDynamicsConstraints (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, const Math::VectorNd & QDDotDesired, ConstraintSet & CS, Math::VectorNd & QDDotOutput, Math::VectorNd & TauOutput, std::vector< Math::SpatialVector > * f_ext = NULL)
An inverse-dynamics operator that can be applied to fully-actuated constrained systems.
Important
Set the actuated degrees-of-freedom using RigidBodyDynamics::ConstraintSet::SetActuationMap prior to calling this function.
Use the function RigidBodyDynamics::isConstrainedSystemFullyActuated to determine if a system is fully actuated or not.
This function implements an inverse-dynamics operator defined by Koch (1) (described in Eqn. 5.20) that can be applied to fully-actuated constraint systems and will solve for a set of physically-consistent and given a desired .
To see test if a constrained system is fully actuated please use the function RigidBodyDynamics::isConstrainedSystemFullyActuated. If the constrained system is not fully actuated then the method RigidBodyDynamics::InverseDynamicsConstraintsRelaxed must be used instead.
For a detailed explanation of the systems which cause this method to fail please read the text following Eqn. 5.20 in Koch's thesis, and the example that is given in Sec. 3 on pg 66. A brief summary is presented below.
To begin,the generalized accelerations are partitioned into actuated parts and unactuated parts
where is an (number of actuated degrees-of-freedom) by (number of degrees of freedom of the unconstrained system) selection matrix that picks out the actuated indices in and
where is an (number of unactuated degrees-of-freedom) by selection matrix that picks out the unactuated indices in . By construction
and thus
We begin by projecting the constrained equations of motion
and adding the constraint that
where is a vector of desired accelerations. By considering only forces that are applied to the actuated parts (that is) we can rearrange the system of equations
By projecting this onto the onto the and spaces
it becomes clear that this system of equations will be singular if loses rank. Thus this method is appropriate to use provided that
The implementation exploits the triangular structure of the matrix which means that only two linear systems of size and are performed which is much faster than solving the KKT matrix directly.
References
Koch KH (2015). Using model-based optimal control for conceptional motion generation for the humannoid robot hrp-2 and design investigations for exo-skeletons. Heidelberg University (Doctoral dissertation).
Parameters
model rigid body model
Q N-element vector of generalized positions
QDot N-element vector of generalized velocities
QDDotDesired N-element vector of desired generalized accelerations (in the above equation)
CS Structure that contains information about the set of kinematic constraints. Note that the 'force' vector is appropriately updated after this function is called so that it contains the Lagrange multipliers.
QDDotOutput N-element vector of generalized accelerations which satisfy the kinematic constraints (in the above equation)
TauOutput N-element vector of generalized forces which satisfy the the equations of motion for this constrained system.
f_ext External forces acting on the body in base coordinates (optional, defaults to NULL)
Definition at line 1775 of file Constraints.cc.
References ConstraintSet::C, RigidBodyDynamics::CalcConstrainedSystemVariables(), ConstraintSet::Fll, ConstraintSet::Flr, ConstraintSet::force, ConstraintSet::Ful, ConstraintSet::Fur, ConstraintSet::G, ConstraintSet::gamma, ConstraintSet::GTl, ConstraintSet::GTu, ConstraintSet::H, ConstraintSet::linear_solver, ConstraintSet::name, ConstraintSet::P, ConstraintSet::S, RigidBodyDynamics::SolveLinearSystem(), ConstraintSet::u, and ConstraintSet::v.
InverseDynamicsConstraintsRelaxed()
RBDL_DLLAPI void InverseDynamicsConstraintsRelaxed (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, const Math::VectorNd & QDDotControls, ConstraintSet & CS, Math::VectorNd & QDDotOutput, Math::VectorNd & TauOutput, std::vector< Math::SpatialVector > * f_ext = NULL)
A relaxed inverse-dynamics operator that can be applied to under-actuated or fully-actuated constrained multibody systems.
Important Set the actuated degrees-of-freedom using RigidBodyDynamics::ConstraintSet::SetActuationMap prior to calling this function.
This function implements the relaxed inverse-dynamics operator defined by Koch [1] and Kudruss [2]. When given a vector of generalized positions, generalized velocities, and desired generalized accelerations will solve for a set of generalized accelerations and forces which satisfy the constrained equations of motion such that the solution is close to a vector of desired acceleration controls
s.t.
In contrast to the RigidBodyDynamics::InverseDynamicsConstraints method, this method can work with underactuated systems. Mathematically this method does not depend on
where is the number of degrees of freedom and is the number of actuated degrees of freedom.
For those readers who are unfamiliar with quadratic programs (QP), like the constrained minimization problem above, read the following important notes. One consequence of this additional flexibility is that the term should now be interpreted as a control vector:
The minimum of the above constrained QP may not be where is the vector of desired accelerations. The terms will pull the solution away from this value and the constraint may make it impossible to exactly satisfy .
Koch's original formulation has been modifed so that setting will yield a solution for that is close to . However, even if an exact solution for exists it will may not be realized using . Iteration may be required.
To solve the above constrained minimization problem we take the derivative of the above system of equations w.r.t. and set the result to zero and solve. This results in the KKT system
This system of linear equations is not solved directly, but instead the null-space formulation presented in Sec. 2.5 of Koch as it is much faster. As with the RigidBodyDynamics::InverseDynamicsConstraints method the matrices and select the actuated and unactuated parts of
, and
, where is a selection matrix that returns the actuated subspace of () and returns the unactuated subspace of ().
This system has an upper block triangular structure which can be seen by noting that
by grouping the upper block into
and by grouping the right hand side into
resulting in
This system can be triangularized by projecting the system into the null space of . First we begin with a QR decomposition of into
and projecting into the space
This allows us to express the previous KKT system as
Though this system is still it can be solved in parts for
and
which is enough to yield a solution for
and finally
This method is less computationally expensive than the KKT system directly since
is of size and is of size which is far smaller than the matrix used in the direct method. As it is relatively inexpensive, the dual variables are also evaluated
and
Note
Two modifications have been made to this implementation to bring the solution to much closer to
The vector has been modifed to so that the term in the upper right hand side is compensated
The weighting matrix has a main diagional that is scaled to be uniformly 100 times larger than the biggest element in M. This will drive the solution closer to without hurting the scaling of the matrix too badly.
The Lagrange multipliers are solved for and stored in the ‘force’ field of the ConstraintSet structure.
The sign of in this documentation is consistent with RBDL and it is equal to times the right hand side of the constraint expressed at the acceleration-level. It is more common to see , in the literature and define as the positive right-hand side of the acceleration equation.
References
Koch KH (2015). Using model-based optimal control for conceptional motion generation for the humannoid robot hrp-2 and design investigations for exo-skeletons. Heidelberg University (Doctoral dissertation).
Kudruss M (under review as of May 2019). Nonlinear model-predictive control for the motion generation of humanoids. Heidelberg University (Doctoral dissertation)
Parameters
model rigid body model
Q N-element vector of generalized positions
QDot N-element vector of generalized velocities
QDDotControls N-element vector of generalized acceleration controls (in the above equation). If the idea of a control vector is unclear please read the above text for additional details.
CS Structure that contains information about the set of kinematic constraints. Note that the 'force' vector is appropriately updated after this function is called so that it contains the Lagrange multipliers.
QDDotOutput N-element vector of generalized accelerations which satisfy the kinematic constraints (in the above equation)
TauOutput N-element vector of generalized forces which satisfy the the equations of motion for this constrained system.
f_ext External forces acting on the body in base coordinates (optional, defaults to NULL)
Definition at line 1860 of file Constraints.cc.
References ConstraintSet::C, RigidBodyDynamics::CalcConstrainedSystemVariables(), ConstraintSet::F, ConstraintSet::force, ConstraintSet::G, ConstraintSet::g, ConstraintSet::gamma, ConstraintSet::GT, ConstraintSet::GT_qr, ConstraintSet::GT_qr_Q, ConstraintSet::H, ConstraintSet::linear_solver, ConstraintSet::name, ConstraintSet::P, ConstraintSet::py, ConstraintSet::pz, ConstraintSet::R, ConstraintSet::Ru, ConstraintSet::S, RigidBodyDynamics::SolveLinearSystem(), ConstraintSet::u, ConstraintSet::v, ConstraintSet::W, ConstraintSet::Winv, ConstraintSet::WinvSC, ConstraintSet::Y, and ConstraintSet::Z.
isBaumgarteStabilizationEnabled()
bool isBaumgarteStabilizationEnabled (unsigned int groupIndex) inline
Parameters
groupIndex the index number of this constraint (see getGroupIndex index functions)
Returns
true if Baumgarte stabilization is enabled
Definition at line 663 of file Constraints.h.
isConstrainedSystemFullyActuated()
RBDL_DLLAPI bool isConstrainedSystemFullyActuated (Model & model, const Math::VectorNd & Q, const Math::VectorNd & QDot, ConstraintSet & CS, std::vector< Math::SpatialVector > * f_ext = NULL)
A method to evaluate if the constrained system is fully actuated.
This method will evaluate the rank of in order to assess if the constrained system is fully actuated or is under actuated. If the system is fully actuated the exact method RigidBodyDynamics::InverseDynamicsConstraints can be used, otherwise only relaxed method RigidBodyDynamics::InverseDynamicsConstraintsRelaxed can be used.
Note
This method uses a relatively slow but accurate method to evaluate the rank.
Parameters
model rigid body model
Q N-element vector of generalized positions
QDot N-element vector of generalized velocities
CS Structure that contains information about the set of kinematic constraints.
f_ext External forces acting on the body in base coordinates (optional, defaults to NULL)
Definition at line 1736 of file Constraints.cc.
References RigidBodyDynamics::CalcConstrainedSystemVariables(), ConstraintSet::G, ConstraintSet::GPT, ConstraintSet::GPT_full_qr, ConstraintSet::H, ConstraintSet::name, ConstraintSet::P, and ConstraintSet::S.
SetActuationMap()
void SetActuationMap (const Model & model, const std::vector< bool > & actuatedDof)
Initializes and allocates memory needed for InverseDynamicsConstraints and InverseDynamicsConstraintsRelaxed.
This function allocates the temporary vectors and matrices needed for the RigidBodyDynamics::InverseDynamicsConstraints and RigidBodyDynamics::InverseDynamicsConstraintsRelaxed methods. In addition, the constant matrices S and P are set here. This function needs to be called once before calling either RigidBodyDynamics::InverseDynamicsConstraints or RigidBodyDynamics::InverseDynamicsConstraintsRelaxed. It does not ever need be called again, unless the actuated degrees of freedom change, or the constraint set changes.
Parameters
model rigid body model
actuatedDof : a vector that is q_size in length (or dof_count in length) which has a 'true' entry for every generalized degree-of freedom that is driven by an actuator and 'false' for every degree-of-freedom that is not.
Definition at line 485 of file Constraints.cc.
SetSolver()
void SetSolver (Math::LinearSolver solver) inline
Specifies which method should be used for solving undelying linear systems.
Definition at line 807 of file Constraints.h.
size()
size_t size () const inline
Returns the number of constraints.
Definition at line 849 of file Constraints.h.
SolveConstrainedSystemDirect()
RBDL_DLLAPI void SolveConstrainedSystemDirect (Math::MatrixNd & H, const Math::MatrixNd & G, const Math::VectorNd & c, const Math::VectorNd & gamma, Math::VectorNd & lambda, Math::MatrixNd & A, Math::VectorNd & b, Math::VectorNd & x, Math::LinearSolver & linear_solver)
Solves the full contact system directly, i.e. simultaneously for contact forces and joint accelerations.
This solves a linear system.
Parameters
H the joint space inertia matrix
G the constraint Jacobian
c the vector of the upper part of the right hand side of the system
gamma the vector of the lower part of the right hand side of the system
lambda result: constraint forces
A work-space for the matrix of the linear system
b work-space for the right-hand-side of the linear system
x work-space for the solution of the linear system
linear_solver type of solver that should be used to solve the system
Definition at line 657 of file Constraints.cc.
References LinearSolverColPivHouseholderQR, LinearSolverHouseholderQR, and LinearSolverPartialPivLU.
SolveConstrainedSystemNullSpace()
RBDL_DLLAPI void SolveConstrainedSystemNullSpace (Math::MatrixNd & H, const Math::MatrixNd & G, const Math::VectorNd & c, const Math::VectorNd & gamma, Math::VectorNd & qddot, Math::VectorNd & lambda, Math::MatrixNd & Y, Math::MatrixNd & Z, Math::VectorNd & qddot_y, Math::VectorNd & qddot_z, Math::LinearSolver & linear_solver)
Solves the contact system by first solving for the joint accelerations and then for the constraint forces.
This methods requires a matrix of the form with the property that can be computed using a QR decomposition (e.g. see code for ForwardDynamicsContactsNullSpace()).
Parameters
H the joint space inertia matrix
G the constraint Jacobian
c the vector of the upper part of the right hand side of the system
gamma the vector of the lower part of the right hand side of the system
qddot result: joint accelerations
lambda result: constraint forces
Y basis for the range-space of the constraints
Z basis for the null-space of the constraints
qddot_y work-space of size
qddot_z work-space of size
linear_solver type of solver that should be used to solve the system
Definition at line 743 of file Constraints.cc.
References LinearSolverColPivHouseholderQR, LinearSolverHouseholderQR, and LinearSolverPartialPivLU.
SolveConstrainedSystemRangeSpaceSparse()
RBDL_DLLAPI void SolveConstrainedSystemRangeSpaceSparse (Model & model, Math::MatrixNd & H, const Math::MatrixNd & G, const Math::VectorNd & c, const Math::VectorNd & gamma, Math::VectorNd & qddot, Math::VectorNd & lambda, Math::MatrixNd & K, Math::VectorNd & a, Math::LinearSolver linear_solver)
Solves the contact system by first solving for the the joint accelerations and then the contact forces using a sparse matrix decomposition of the joint space inertia matrix.
This method exploits the branch-induced sparsity by the structure preserving decomposition described in RBDL, Section 6.5.
Parameters
model rigid body model
H the joint space inertia matrix
G the constraint Jacobian
c the vector of the upper part of the right hand side of the system
gamma the vector of the lower part of the right hand side of the system
qddot result: joint accelerations
lambda result: constraint forces
K work-space for the matrix of the constraint force linear system
a work-space for the right-hand-side of the constraint force linear system
linear_solver type of solver that should be used to solve the constraint force system
Definition at line 704 of file Constraints.cc.
References RigidBodyDynamics::Math::SparseFactorizeLTL(), RigidBodyDynamics::Math::SparseSolveLTx(), and RigidBodyDynamics::Math::SparseSolveLx().
Variable Documentation
A
Math::MatrixNd A
Workspace for the Lagrangian left-hand-side matrix.
Definition at line 915 of file Constraints.h.
a
Math::VectorNd a
Workspace for the accelerations of due to the test forces.
Definition at line 961 of file Constraints.h.
b
Math::VectorNd b
Workspace for the Lagrangian right-hand-side.
Definition at line 917 of file Constraints.h.
bound
bool bound
Whether the constraint set was bound to a model (mandatory!).
Definition at line 859 of file Constraints.h.
C
Math::VectorNd C
Workspace for the coriolis forces.
Definition at line 908 of file Constraints.h.
cache
ConstraintCache cache
Definition at line 988 of file Constraints.h.
constraints
std::vector< std::shared_ptr<Constraint> > constraints
Definition at line 883 of file Constraints.h.
constraintType
std::vector<ConstraintType> constraintType
Definition at line 862 of file Constraints.h.
contactConstraints
std::vector< std::shared_ptr<ContactConstraint> > contactConstraints
Definition at line 885 of file Constraints.h.
d_a
std::vector<Math::SpatialVector> d_a
Workspace for the acceleration due to the test force.
Definition at line 976 of file Constraints.h.
d_d
Math::VectorNd d_d
Workspace when applying constraint forces.
Definition at line 984 of file Constraints.h.
d_IA
std::vector<Math::SpatialMatrix> d_IA
Workspace for the inertia when applying constraint forces.
Definition at line 980 of file Constraints.h.
d_multdof3_u
std::vector<Math::Vector3d> d_multdof3_u
Definition at line 986 of file Constraints.h.
d_pA
std::vector<Math::SpatialVector> d_pA
Workspace for the bias force due to the test force.
Definition at line 974 of file Constraints.h.
d_u
Math::VectorNd d_u
Definition at line 977 of file Constraints.h.
d_U
std::vector<Math::SpatialVector> d_U
Workspace when applying constraint forces.
Definition at line 982 of file Constraints.h.
err
Math::VectorNd err
Position error for the Baumgarte stabilization
Definition at line 891 of file Constraints.h.
errd
Math::VectorNd errd
Velocity error for the Baumgarte stabilization
Definition at line 893 of file Constraints.h.
F
Math::MatrixNd F
Definition at line 935 of file Constraints.h.
f_ext_constraints
std::vector<Math::SpatialVector> f_ext_constraints
Workspace for the actual spatial forces.
Definition at line 969 of file Constraints.h.
f_t
std::vector<Math::SpatialVector> f_t
Workspace for the test forces.
Definition at line 967 of file Constraints.h.
Fll
Math::MatrixNd Fll
Definition at line 936 of file Constraints.h.
Flr
Math::MatrixNd Flr
Definition at line 936 of file Constraints.h.
force
Math::VectorNd force
The Lagrange multipliers, which due to some careful normalization in the formulation of constraints are the constraint forces.
Definition at line 897 of file Constraints.h.
Ful
Math::MatrixNd Ful
Definition at line 936 of file Constraints.h.
Fur
Math::MatrixNd Fur
Definition at line 936 of file Constraints.h.
G
Math::MatrixNd G
Workspace for the constraint Jacobian.
Definition at line 912 of file Constraints.h.
g
Math::VectorNd g
Definition at line 940 of file Constraints.h.
gamma
Math::VectorNd gamma
Workspace of the right hand side of the acceleration equation.
Definition at line 910 of file Constraints.h.
GPT
Math::MatrixNd GPT
Definition at line 950 of file Constraints.h.
GPT_full_qr
Eigen::FullPivHouseholderQR<Math::MatrixNd> GPT_full_qr
Definition at line 947 of file Constraints.h.
GT
Math::MatrixNd GT
Definition at line 938 of file Constraints.h.
GT_qr
Eigen::HouseholderQR<Math::MatrixNd> GT_qr
Workspace for the QR decomposition of the null-space method.
Definition at line 946 of file Constraints.h.
GT_qr_Q
Math::MatrixNd GT_qr_Q
Definition at line 949 of file Constraints.h.
GTl
Math::MatrixNd GTl
Definition at line 939 of file Constraints.h.
GTu
Math::MatrixNd GTu
Definition at line 939 of file Constraints.h.
H
Math::MatrixNd H
Workspace for the joint space inertia matrix.
Definition at line 906 of file Constraints.h.
idGroupMap
std::map< unsigned int, unsigned int> idGroupMap
Definition at line 868 of file Constraints.h.
impulse
Math::VectorNd impulse
Constraint impulses along the constraint directions.
Definition at line 899 of file Constraints.h.
K
Math::MatrixNd K
Workspace for the Inverse Articulated-Body Inertia.
Definition at line 959 of file Constraints.h.
linear_solver
Math::LinearSolver linear_solver
Method that should be used to solve internal linear systems.
Definition at line 857 of file Constraints.h.
loopConstraints
std::vector< std::shared_ptr<LoopConstraint> > loopConstraints
Definition at line 887 of file Constraints.h.
name
std::vector<std::string> name
Definition at line 864 of file Constraints.h.
nameGroupMap
std::map< std::string, unsigned int > nameGroupMap
Definition at line 866 of file Constraints.h.
P
Math::MatrixNd P
Selection matrix for the non-actuated parts of the model.
Definition at line 925 of file Constraints.h.
point_accel_0
std::vector<Math::Vector3d> point_accel_0
Workspace for the default point accelerations.
Definition at line 971 of file Constraints.h.
py
Math::VectorNd py
Definition at line 942 of file Constraints.h.
pz
Math::VectorNd pz
Definition at line 943 of file Constraints.h.
QDDot_0
Math::VectorNd QDDot_0
Workspace for the default accelerations.
Definition at line 965 of file Constraints.h.
QDDot_t
Math::VectorNd QDDot_t
Workspace for the test accelerations.
Definition at line 963 of file Constraints.h.
qddot_y
Math::VectorNd qddot_y
Definition at line 954 of file Constraints.h.
qddot_z
Math::VectorNd qddot_z
Definition at line 955 of file Constraints.h.
R
Math::MatrixNd R
Definition at line 953 of file Constraints.h.
Ru
Math::MatrixNd Ru
Definition at line 941 of file Constraints.h.
S
Math::MatrixNd S
Selection matrix for the actuated parts of the model needed for the inverse-dynamics-with-constraints operator
Definition at line 923 of file Constraints.h.
u
Math::VectorNd u
Definition at line 932 of file Constraints.h.
userDefinedIdGroupMap
std::map< unsigned int, unsigned int> userDefinedIdGroupMap
Definition at line 867 of file Constraints.h.
v
Math::VectorNd v
Definition at line 933 of file Constraints.h.
v_plus
Math::VectorNd v_plus
The velocities we want to have along the constraint directions.
Definition at line 901 of file Constraints.h.
W
Math::MatrixNd W
Matrix that holds the relative cost of deviating from the desired accelerations
Definition at line 928 of file Constraints.h.
Winv
Math::MatrixNd Winv
Definition at line 929 of file Constraints.h.
WinvSC
Math::VectorNd WinvSC
Definition at line 930 of file Constraints.h.
x
Math::VectorNd x
Workspace for the Lagrangian solution.
Definition at line 919 of file Constraints.h.
Y
Math::MatrixNd Y
Definition at line 951 of file Constraints.h.
Z
Math::MatrixNd Z
Definition at line 952 of file Constraints.h.